- name: bug
  description: Something isn't working
  color: d73a4a
- name: documentation
  description: Improvements or additions to documentation
  color: 0075ca
- name: duplicate
  description: This issue or pull request already exists
  color: cfd3d7
- name: teste
  description: testando
  color: 0000ff
  - name: teste2
  description: testando
  color: 0000ff
  - name: teste3
  description: testando
  color: 0000ff
  - name: teste4
  description: testando
  color: 0000ff
  - name: teste5
  description: testando
  color: 0000ff
  - name: teste6
  description: testando
  color: 0000ff