name: Sync labels
on:
  push:
    paths:
      - path/to/manifest/labels.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${ GITHUB_TOKEN }
        with:
          manifest: path/to/manifest/labels.yml